import { Container, Flex, Stack } from "@chakra-ui/react";
import Nav from "./Nav";
import Footer from "./Footer";
import Head from "next/head";

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Hoang Le - hoangulrich.io</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />
      <Container maxW="container.xl" mt={["20", "20", "36", "36"]}>
        <Stack spacing="24">{children}</Stack>
      </Container>
      <Footer />
    </>
  );
};

export default Layout;
