import Head from "next/head";
import Layout from "../components/Layout";
import Introduction from "../components/Introduction";

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Hoang Le - hoangulrich.io</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Introduction />
    </Layout>
  );
}
